from pydantic import BaseModel
from typing import Optional
from uuid import UUID
from datetime import datetime # For timestamp fields in response

# Import base schemas and timestamp schema
from .base_schema import BiodataBaseSchema, ContactInformationBaseSchema, EmergencyContactBaseSchema, TimestampSchema

# --- Patient Schemas ---

class PatientBaseSchema(BaseModel):
    """
    Base schema for patient data, containing shared nested structures.
    """
    biodata: BiodataBaseSchema
    contact_information: ContactInformationBaseSchema
    emergency_contact: EmergencyContactBaseSchema

class PatientCreateSchema(PatientBaseSchema):
    """
    Schema for creating a new patient.
    'patient_folder_number' is generated by the server, so it's not included here.
    ID and timestamps are also server-generated.
    """
    # All fields are inherited from PatientBaseSchema.
    # No patient_folder_number here; it's generated by the service.
    pass

class PatientUpdateSchema(BaseModel):
    """
    Schema for updating an existing patient. All fields are optional.
    'patient_folder_number' is generally not updatable directly by client.
    """
    biodata: Optional[BiodataBaseSchema] = None
    contact_information: Optional[ContactInformationBaseSchema] = None
    emergency_contact: Optional[EmergencyContactBaseSchema] = None


class PatientResponseSchema(PatientBaseSchema, TimestampSchema):
    """
    Schema for representing a patient in API responses.
    Includes server-generated fields like id, patient_folder_number, and timestamps.
    """
    id: UUID
    patient_folder_number: str

    # Inherits biodata, contact_information, emergency_contact from PatientBaseSchema
    # Inherits date_created, date_updated, date_deleted from TimestampSchema
   
    class Config:
        from_attributes = True
        